// src/components/simple/AiToolCategory.vue
<script setup lang="ts">
import type { Category } from '@/types';
import { RouterLink } from 'vue-router';

defineProps<{
  category: Category
}>()
</script>

<template>
  <router-link :to="'/ai-tool-categories/' + encodeURI(category.title)"
    class="flex text-secondary rounded-xl p-5 gap-2 shadow-lg">
    <img src="@/assets/text.svg" class="h-16 w-16" alt="">

    <div class="flex flex-col justify-between">
      <p class="text-lg font-bold">{{ category.title }}</p>
      <p class="">{{ category.numTools }} Tools</p>
    </div>
  </router-link>
</template>

// src/components/simple/AiToolCategory.tsx
import React from 'react';
import TextIcon from '@/assets/text.svg';
import { Link } from 'react-router-dom';

import { Category } from '@/types';

interface AiToolCategoryProps {
  category: Category;
}

const AiToolCategory: React.FC<AiToolCategoryProps> = ({ category }) => {
  return (
    <Link
      to={`/ai-tool-categories/${encodeURI(category.title)}`}
      className="flex text-secondary rounded-xl p-5 gap-2 shadow-lg"
    >
      <img src={TextIcon} className="h-16 w-16" alt="" />

      <div className="flex flex-col justify-between">
        <p className="text-lg font-bold">{category.title}</p>
        <p>{category.numTools} Tools</p>
      </div>
    </Link>
  );
};

export default AiToolCategory;
