// src/components/simple/CountryCard.tsx
import { Button } from '@/components/ui/button';
import { Country } from '@/types';
import React from 'react';
import { Link } from 'react-router-dom';

interface CountryCardProps {
  country: Country;
}

const CountryCard: React.FC<CountryCardProps> = ({ country }) => {
  return (
    <div className="rounded-3xl p-4 shadow-[0px_0px_10px_5px_#00000024]">
      <div className="relative">
        <img
          src={country.imageUrl}
          className="rounded-xl w-full h-52"
          alt="Country Cover Image"
        />
        <Button
          asChild
          className="absolute left-1/2 -translate-x-1/2 -bottom-2"
        >
          <Link to={`/countries/${country.name}`}>Visit Country</Link>
        </Button>
      </div>
      <p className="mt-3 text-sm lg:text-2xl font-bold text-wrap text-center object-contain">
        {country.name.toUpperCase()}
      </p>
    </div>
  );
};

export default CountryCard;

// src/components/simple/CountryCard.vue
<script setup lang="ts">
import Button from '@/components/ui/button/Button.vue';
import type { Country } from '@/types';

defineProps<{
  country: Country,
}>()
</script>

<template>
  <div class="rounded-3xl p-4 shadow-[0px_0px_10px_5px_#00000024]">
    <div class="relative">
      <img :src="country.imageUrl" class="rounded-xl w-full h-52" alt="Country Cover Image">
      <Button as="a" :href="'/countries/' + country.name" class="absolute left-1/2 -translate-x-1/2 -bottom-2">Visit
        Country</Button>
    </div>
    <p class="mt-3 text-sm lg:text-2xl font-bold text-wrap text-center object-contain">{{ country.name.toUpperCase() }}
    </p>
  </div>
</template>
