// src/components/simple/ResourceCard.tsx
import { Resource } from '@/types';
import React from 'react';
import { Link } from 'react-router-dom';

interface ResourceCardProps {
  resource: Resource;
}

const ResourceCard: React.FC<ResourceCardProps> = ({ resource }) => {
  return (
    <Link to={`/resources/${encodeURI(resource.slug)}`}>
      <img
        src={resource.imageUrl}
        alt={resource.imageAlt}
        className="h-72 w-full italic object-cover rounded-3xl"
      />

      <h3 className="mt-8 text-2xl text-secondary font-bold">
        {resource.title}
      </h3>
    </Link>
  );
};

export default ResourceCard;

// src/components/simple/ResourceCard.vue
<script setup lang="ts">
import type { Resource } from '@/types';

defineProps<{
  resource: Resource;
}>()
</script>

<template>
  <a :href="/resources/ + resource.slug">
    <img :src="resource.imageUrl" :alt="resource.imageAlt" class="h-72 w-full italic object-cover rounded-3xl">

    <h3 class="mt-8 text-2xl text-secondary font-bold">{{ resource.title }}</h3>
  </a>
</template>
