// src/components/layout/MainFooter.vue
<script setup lang="ts">
import { FacebookIcon, LinkedinIcon } from 'lucide-vue-next';
import { RouterLink } from 'vue-router';
import DiscordIcon from '../simple/icons/DiscordIcon.vue';
import TiktokIcon from '../simple/icons/TiktokIcon.vue';
import WhatsappIcon from '../simple/icons/WhatsappIcon.vue';
</script>

<template>
  <footer class="bg-secondary text-white">
    <div
      class="py-14 px-10 grid grid-cols-[repeat(auto-fit,_minmax(250px,_1fr))] content-center lg:justify-items-end lg:grid-cols-[45%_18%_18%_18%] gap-y-10">
      <div>
        <img src="@/assets/logo.svg" alt="AAN logo" class="italic mb-2 h-10 lg:h-14" />

        <p class="self-start mb-8 2xl:mr-0">African AI Network is a community-driven network that brings together
          AI
          enthusiasts
          from
          all 54
          African
          countries. Join this vibrant network to share knowledge, collaborate on projects and stay updated with the
          latest AI developers in the world.</p>

        <div class="w-fit">
          <a class="mb-5 text-center block bg-primary text-white rounded-full px-8 py-2 w-full" href="/about">More</a>

          <div class="flex gap-6">
            <a href="https://www.facebook.com/groups/1490131391564053/?ref=share" title="Visit our Facebook Page">
              <p class="sr-only">Visit our Facebook Page</p>
              <facebook-icon height="20" width="20" />
            </a>
            <a href="https://www.linkedin.com/groups/9802179" title="Visit our LinkedIn Account">
              <p class="sr-only">Visit our LinkedIn Account</p>
              <linkedin-icon height="20" width="20" />
            </a>
            <a href="https://discord.gg/zytPSazu6S" title="Join our Discord Channel">
              <p class="sr-only">Join our Discord Channel</p>
              <discord-icon height="20" width="20" />
            </a>
            <a href="https://chat.whatsapp.com/G2khjYh9eVOKOGXaoXEDDZ" title="Join our Whatsapp community">
              <p class="sr-only">Join our Whatsapp community</p>
              <whatsapp-icon height="20" width="20" />
            </a>
            <a href="https://tiktok.com/@african.ai.network" title="Visit our Tiktok Channel">
              <p class="sr-only">Visit our Tiktok Channel</p>
              <tiktok-icon height="20" width="20" />
            </a>
          </div>
        </div>
      </div>
      <div>
        <h3 class="mb-4 font-bold text-lg">AI Tool Categories</h3>
        <ul class="flex flex-col gap-y-2">
          <li>
            <a href="/ai-tools">Business & Productivity</a>
          </li>
          <li>
            <a href="/ai-tools">Design</a>
          </li>
          <li>
            <a href="/ai-tools">Education</a>
          </li>
          <li>
            <a href="/ai-tools">Research</a>
          </li>
        </ul>
      </div>
      <div>
        <h3 class="mb-4 font-bold text-lg">Resources</h3>
        <ul class="flex flex-col gap-y-2">
          <li>
            <a href="#">Courses</a>
          </li>
          <li>
            <a href="#">Blog Posts</a>
          </li>
        </ul>
      </div>
      <div>
        <h3 class="mb-4 font-bold text-lg">Company</h3>
        <ul class="flex flex-col gap-y-2">
          <li>
            <router-link to="/about">About Us</router-link>
          </li>
          <li>
            <a href="#">Contact Us</a>
          </li>
        </ul>
      </div>
    </div>

    <div class="flex flex-wrap p-5 gap-3 border border-white border-r-0 border-l-0">
      <p>2024 African AI Network LLC, All rights reserved.</p>
      <a href="#" class="underline hover:text-blue-300 focus-visible:text-blue-300 transition-colors">Privacy Policy</a>
      <a href="#" class="underline hover:text-blue-300 focus-visible:text-blue-300 transition-colors">Terms of
        Service</a>
    </div>
  </footer>
</template>

// src/components/layout/MainFooter.tsx
import Logo from '@/assets/logo.svg';
import { FacebookIcon, LinkedinIcon } from 'lucide-react';
import React from 'react';
import { Link } from 'react-router-dom';
import DiscordIcon from '../simple/icons/DiscordIcon';
import TiktokIcon from '../simple/icons/TiktokIcon';
import WhatsappIcon from '../simple/icons/WhatsappIcon';

const MainFooter: React.FC = () => {
  return (
    <footer className="bg-secondary text-white">
      <div className="py-14 px-10 grid grid-cols-[repeat(auto-fit,_minmax(250px,_1fr))] content-center lg:justify-items-end lg:grid-cols-[45%_18%_18%_18%] gap-y-10">
        <div>
          <img src={Logo} alt="AAN logo" className="italic mb-2 h-10 lg:h-14" />

          <p className="self-start mb-8 2xl:mr-0">
            African AI Network is a community-driven network that brings
            together AI enthusiasts from all 54 African countries. Join this
            vibrant network to share knowledge, collaborate on projects and stay
            updated with the latest AI developers in the world.
          </p>

          <div className="w-fit">
            <a
              className="mb-5 text-center block bg-primary text-white rounded-full px-8 py-2 w-full"
              href="/about"
            >
              More
            </a>

            <div className="flex gap-6">
              <a
                href="https://www.facebook.com/groups/1490131391564053/?ref=share"
                title="Visit our Facebook Page"
              >
                <p className="sr-only">Visit our Facebook Page</p>
                <FacebookIcon height={20} width={20} />
              </a>
              <a
                href="https://www.linkedin.com/groups/9802179"
                title="Visit our LinkedIn Account"
              >
                <p className="sr-only">Visit our LinkedIn Account</p>
                <LinkedinIcon height={20} width={20} />
              </a>
              <a
                href="https://discord.gg/zytPSazu6S"
                title="Join our Discord Channel"
              >
                <p className="sr-only">Join our Discord Channel</p>
                <DiscordIcon height={20} width={20} />
              </a>
              <a
                href="https://chat.whatsapp.com/G2khjYh9eVOKOGXaoXEDDZ"
                title="Join our Whatsapp community"
              >
                <p className="sr-only">Join our Whatsapp community</p>
                <WhatsappIcon height={20} width={20} />
              </a>
              <a
                href="https://tiktok.com/@african.ai.network"
                title="Visit our Tiktok Channel"
              >
                <p className="sr-only">Visit our Tiktok Channel</p>
                <TiktokIcon height={20} width={20} />
              </a>
            </div>
          </div>
        </div>
        <div>
          <h3 className="mb-4 font-bold text-lg">AI Tool Categories</h3>
          <ul className="flex flex-col gap-y-2">
            <li>
              <a href="/ai-tools">Business & Productivity</a>
            </li>
            <li>
              <a href="/ai-tools">Design</a>
            </li>
            <li>
              <a href="/ai-tools">Education</a>
            </li>
            <li>
              <a href="/ai-tools">Research</a>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="mb-4 font-bold text-lg">Resources</h3>
          <ul className="flex flex-col gap-y-2">
            <li>
              <a href="#">Courses</a>
            </li>
            <li>
              <a href="#">Blog Posts</a>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="mb-4 font-bold text-lg">Company</h3>
          <ul className="flex flex-col gap-y-2">
            <li>
              <Link to="/about">About Us</Link>
            </li>
            <li>
              <a href="#">Contact Us</a>
            </li>
          </ul>
        </div>
      </div>

      <div className="flex flex-wrap p-5 gap-3 border border-white border-r-0 border-l-0">
        <p>2024 African AI Network LLC, All rights reserved.</p>
        <a
          href="#"
          className="underline hover:text-blue-300 focus-visible:text-blue-300 transition-colors"
        >
          Privacy Policy
        </a>
        <a
          href="#"
          className="underline hover:text-blue-300 focus-visible:text-blue-300 transition-colors"
        >
          Terms of Service
        </a>
      </div>
    </footer>
  );
};

export default MainFooter;
