// src/pages/AiToolsPage.vue
<script setup lang="ts">
import NavBar from '@/components/layout/NavBar.vue';

import AiToolsCategories from '@/components/ai-tools/sections/AiToolsCategories.vue';
import HeroSection from '@/components/ai-tools/sections/HeroSection.vue';
</script>

<template>
  <header>
    <nav-bar :blue-bg="true" />
  </header>

  <main class="min-h-dvh pt-[200px] xl:pt-[100px] 2xl:pt-[150px]">
    <hero-section />
    <ai-tools-categories />
  </main>
</template>

// src/pages/AiToolsPage.tsx
import AiToolsCategories from '@/components/ai-tools/sections/AiToolCategories';
import HeroSection from '@/components/ai-tools/sections/HeroSection';
import Navbar from '@/components/layout/NavBar';

const CountriesPage = () => {
  return (
    <>
      <header>
        <Navbar />
      </header>

      <main className="min-h-dvh pt-[150px] xl:pt-[100px] 2xl:pt-[150px]">
        <HeroSection />
        <AiToolsCategories />
      </main>
    </>
  );
};

export default CountriesPage;
