// src/pages/HomePage.tsx
import FeaturesAndPartnersSection from '@/components/home/sections/FeaturesAndPartnersSection';
import HeroSection from '@/components/home/sections/HeroSection';
import ResourcesSection from '@/components/home/sections/ResourcesSection';
import ReviewsSection from '@/components/home/sections/ReviewsSection';
import Navbar from '@/components/layout/NavBar';

const HomePage = () => {
  return (
    <>
      <header>
        <Navbar transparent />
      </header>

      <main>
        <HeroSection />
        <FeaturesAndPartnersSection />
        <ReviewsSection />
        <ResourcesSection />
      </main>
    </>
  );
};

export default HomePage;

// src/pages/HomePage.vue
<script setup lang="ts">
import NavBar from '@/components/layout/NavBar.vue';

import FeaturesAndPartnersSection from '@/components/home/sections/FeaturesAndPartnersSection.vue';
import HeroSection from '@/components/home/sections/HeroSection.vue';
import ReviewsSection from '@/components/home/sections/ReviewsSection.vue';
import ResourcesSection from '@/components/home/sections/ResourcesSection.vue';
</script>

<template>
  <header>
    <nav-bar transparent />
  </header>

  <main>
    <hero-section />
    <features-and-partners-section />
    <reviews-section />
    <resources-section />
  </main>
</template>
